### ISSUE TITLE
Start Debugger on Application Launch

### ISSUE THREAD

**Issue by seesemichaelj** [fabiospampinato/vscode-statusbar-debugger#1]
I believe that you should autostart the debugger when you run the application (i.e. F5)

**Comment by fabiospampinato** [comment]
I wrote about this in the readme, look at the hint named `Remap start/stop shortcuts`.

Basically it's possible to do it, but you have to edit your keybindings.

**Comment by seesemichaelj** [comment]
Sorry for not RTFM'ing haha

**Comment by fabiospampinato** [comment]
I've just pushed an update that uses the new APIs for auto-detecting when a debug session starts/stops 💪
