### ISSUE TITLE
floating default debugger showing again

### ISSUE THREAD

**Issue by Slos** [fabiospampinato/vscode-statusbar-debugger#11]
Hi Fabio,

After VS code updated itself to the latest version (1.25.0) I am seeing the default floating debugger bar again. looks like the setting '"debug.hideActionBar": true' is being ignored... could you please have a look at this situation?

I don't understand why the VS code team have not dealt with this thing yet, I hate the floating debugger and I don't think I'm the only one :)

Kind regards,

Filip

**Comment by fabiospampinato** [comment]
Hey,

There has been some development in this front actually, but their solutions for this problem are quite bad I think, you can now put the toolbar into the sidebar (not in a actual whole line for itself, but rather next to the title, it looks awful) or below the tab bar (better, but it's still messy, as I think it may get on top of your code and I don't even know how the whole thing works when you're also displaying the find widget in there).

They changed the setting for disabling the toolbar, you now have to put this: `"debug.toolBarLocation": "hidden"` into your settings.

I've updated the readme accordingly, thank you.
