### ISSUE TITLE
"statusbarDebugger.command: auto" prompts to create a new config

### ISSUE THREAD

**Issue by Spown** [fabiospampinato/vscode-statusbar-debugger#13]
After the couple recent VSCode updates, the bug icon got bugged, pun (not) intended. 

1. On Program start it doesn't show the name of the last debug config used as it did before (or at least I think it did...). Only after running a session it assumes the value, but loses it on session stop:
![](https://drive.google.com/uc?id=19DiBfFK8jq6FQRgiYbBHm1piyFUwOA6d)

2. After clicking it, instead of calling the palette to choose a config it opens the ``launch.json`` and prompts to create a new config, even if there are several to choose from.
![](https://drive.google.com/uc?id=1-f-7XFGypp_h3Iii4O_7P2Lx52g4PRZi)

Using ``start`` or ``select`` configs seems to work as intended.

Thank you.

**Comment by fabiospampinato** [comment]
> On Program start it doesn't show the name of the last debug config used as it did before (or at least I think it did...).

I don't think it ever did that, did it? 🤔 

> After clicking it, instead of calling the palette to choose a config it opens the launch.json and prompts to create a new config, even if there are several to choose from.

Strange, it sounds like you're maybe clicking the bug icon while the focused editor is the Settings editor or something?

**Comment by Spown** [comment]
>I don't think it ever did that, did it? 🤔

Maybe not, but it's not that important to reinstall previous VSC+ext versions to check whether it did. so just disregard that part.

>clicking the bug icon while the focused editor is the Settings editor or something?

No, it doesn't matter what is focused right now - it always does it when set to ``auto``

> ..."auto" execute `debugLauncher.auto` or start debugging if it detects only one configuration and ask for a selection if there are more than one. ...

Can it be related to this debugLauncher extension? I don't use it...

**Comment by Spown** [comment]
![](https://drive.google.com/uc?id=17jtTjucbBWO21c18F6lcj9s9BseL5w4a)
Also it took me some time to figure out what is meant by ``debugLauncher.auto``. When reading the option description in the settings without reading the readme for the ``statusbar-debugger`` extension (and I didn't read the updated version since I've already did it when I was installing it) - it is not clear whether it refers to some setting of ``statusbar-debugger`` or VSCode itself or anything else. I think mentioning in the setting description that ``debugLauncher`` is an another extension wouldn't harm as well.

**Comment by fabiospampinato** [comment]
Fixed in v2.0.6, and improved the description for the `statusbarDebugger.command` setting.

Thank you.
