### ISSUE TITLE
Feature request: reopen explorer view when stopping

### ISSUE THREAD

**Issue by Gruntfuggly** [fabiospampinato/vscode-statusbar-debugger#14]
I like the fact that this extension allows you to start debugging without selecting the debug view first. If it could go back to the explorer view when stopping, that would be even better.

It should probably be optional as I expect not everybody would want to.

**Comment by fabiospampinato** [comment]
That sounds like a useful idea, but it's also pretty specific, I'm not sure the addition of an extra setting just for this is worth it.

If there's a way to execute a custom command after another one has been executed I think it would be better to do it this way, but I'm not sure VSC's APIs allow this 🤔 

I'll think about that, thanks for the suggestion!

**Comment by fabiospampinato** [comment]
Too specific, configure a macro via the macro extension for that.
