### ISSUE TITLE
Background color of the tool in the statutsbar

### ISSUE THREAD

**Issue by jtrujillo7** [fabiospampinato/vscode-statusbar-debugger#16]
Wow, what a relief to get rid of the default debug toolbar.

I am not sure if it's possible, if it is, but would you consider allowing a setting to change de background and color of the tool? that would make it stand up among other items and give a more direct idea of the debugging state.

**Comment by fabiospampinato** [comment]
There's no API for this AFAIK.

**Comment by fabiospampinato** [comment]
Let's keep this open as a reminder.

**Comment by fabiospampinato** [comment]
Closing as this is probably never going to be possible.
