### ISSUE TITLE
Support default configurations

### ISSUE THREAD

**Issue by lukaszpolowczyk** [fabiospampinato/vscode-statusbar-debugger#17]
If I have more than one launch, after clicking "Start Debugging" I have to choose launch.
I want it to always start the default launch, without selecting.

This behavior can be an option in the extension settings.

**Comment by fabiospampinato** [comment]
What's the default configuration?

**Comment by lukaszpolowczyk** [comment]
When you click Run> Start Debugging, the last used launch is always selected.
The default should be last used. The one that turns on when you click Run> Start Debugging.

**Comment by fabiospampinato** [comment]
The extension would basically never ask to pick a configuration then when multiple ones are available, right? 🤔

**Comment by lukaszpolowczyk** [comment]
Yes, when there are many launches.
I write about it all the time. : D

I want, when there are many launchers, that the last used fire up after one click on the icon in the status bar (the icon of your extension).

Probably this behavior should be optional:
I write about it all the time. : D

I want, when there are many launchers, that the last used fire up after one click on the icon in the status bar (the icon of your extension).

Probably this behavior should be optional:
By default, it should display a list of launchers, and when option checked, it should launch the last launcher used immediately.

**Comment by lukaszpolowczyk** [comment]
Yes, when there are many launches.
I write about it all the time. :D

I want, when there are many launchers, that the last used fire up after one click on the icon in the status bar (the icon of your extension).

Probably this behavior should be optional:
By default, it should display a list of launchers, and when option checked, it should launch the last launcher used immediately

**Comment by fabiospampinato** [comment]
> By default, it should display a list of launchers, and when option checked, it should launch the last launcher used immediately

Maybe, yeah. I'd like it much better if we could bound this behavior to a Ctrl+Click or something, I don't think that's possible though.

**Comment by fabiospampinato** [comment]
The default command is customizable, potentially it could be replaced with another one that works like you want it to, I don't see this getting implemented by the extension itself.
