### ISSUE TITLE
Play Button Should be Pause When Code is Running

### ISSUE THREAD

**Issue by seesemichaelj** [fabiospampinato/vscode-statusbar-debugger#2]
The play button should be (and act as) a pause button when the code isn't at a breakpoint. This helps if I want to pause the application when it's "hanging" to find out where in the code it is hanging at.

**Comment by fabiospampinato** [comment]
I agree, but there's currently now way of detecting if code execution is paused or not, this issue is blocked by the issue you referenced.

**Comment by fabiospampinato** [comment]
The `pause` action is now enabled by default.

I managed to make a convincing pause icon via a combination of unicode characters.
