### ISSUE TITLE
Consider timing of asking for donations

### ISSUE THREAD

**Issue by working-name** [fabiospampinato/vscode-statusbar-debugger#20]
Hi there,

Just installed your extension and as soon as I enabled debug in vscode it asked me for a donation. I could barely see the buttons at the bottom, trying to determine the usefulness of this extension. You're 100% going to get a no, because you didn't allow time to figure out if I find it interesting. Then unless you keep popping a notification on every run which is equally annoying, you'll never make me aware of the fact that the plugin needs monetary support again. Lose-lose.

So my suggestion is that you allow the user a couple days of use before asking if they find it useful enough to donate. Otherwise I feel like you're doing yourself a disservice by asking right away.

**Comment by fabiospampinato** [comment]
There is a check for this already actually, but I forgot to consider the case where there might be multiple windows open 🤦  I'll get that fixed, thanks!
