### ISSUE TITLE
Display Shortcuts

### ISSUE THREAD

**Issue by ConstantinosA** [fabiospampinato/vscode-statusbar-debugger#21]
it would be useful if in mouseover of each button also display the Shortcut.
example on the continue button mouseover to display "Continue (F5)" instead of displaying only "Continue".

**Comment by fabiospampinato** [comment]
I'm not sure if there are APIs for implementing that 🤔

**Comment by fabiospampinato** [comment]
There's now a setting, `statusbarDebugger.actionsTooltips`, that can be used to add shortcuts to tooltips. 

I still think it's something that vscode itself should take care of though.
