### ISSUE TITLE
Command [x] is currently not enabled and can not be run.

### ISSUE THREAD

**Issue by gnowland** [fabiospampinato/vscode-statusbar-debugger#3]
For example:
`Warn: Command 'Continue' is currently not enabled and can not be run.`

I think it would be really helpful if the currently disabled commands were grayed out... is this possible?

**Comment by fabiospampinato** [comment]
Unfortunately at the moment there's no way of knowing if a debug session is paused or not.

Having that information we could gray-out those icons and merge pause/play into a single button.

We'll have to wait for [this](https://github.com/Microsoft/vscode/issues/30810) upstream issue.

**Comment by gnowland** [comment]
Ah, I figured there was probably an API functionality limitation regarding this. Thanks for the reply!

**Comment by fabiospampinato** [comment]
Duplicate of #15
