### ISSUE TITLE
The status bar does not change state after the first Debug Start

### ISSUE THREAD

**Issue by mikailcf** [fabiospampinato/vscode-statusbar-debugger#6]
When starting a debug session the status bar changes to the Active state, but it doesn't change back neither by using the status bar button nor the menu action:

![debug_status_bug_5fps](https://user-images.githubusercontent.com/409058/30251068-4182ff9c-962f-11e7-902d-556fc26253a1.gif)

Plus: when using `vscode['debug'].onDidChangeActiveDebugSession(() => this.update());` instead of the `vscode['debug'].onDidStartDebugSession(() => this.update(true));
vscode['debug'].onDidTerminateDebugSession(() => this.update(false));` it works as (I presume) intended:

![debug_status_fix_5fps](https://user-images.githubusercontent.com/409058/30251091-b88b2484-962f-11e7-868e-0722e6eacda4.gif)

OS Version: macOS 10.12.6
VS Code Version: 1.16.0

**Comment by fabiospampinato** [comment]
Thanks very much for the information!

Does the extension work if instead of doing `Start Without Debugging` you do a `Start Debugging`?

I wasn't aware of the existence of this `Start Without Debugging` command, what does it do exactly? I find it very confusing that it's under the `Debug` menu, I've not idea what `Debug Without Debugging` is supposed to mean.

**Comment by mikailcf** [comment]
Indeed it does work with `Start Debugging`. Starting and stoping via the status bar and also via the menu actions.

`Start without debugging` is basically a `Run` action (the Code command for it is `workbench.action.debug.run`). It runs the same launch configuration as the `Start Debugging` but it doesn't try to bind Code to the debug port, ignoring any breakpoints and whatnot.

**Comment by fabiospampinato** [comment]
This should be fixed with v1.1.2.

It wasn't working properly due to a few bugs I've found in VSC, I've opened an upstream [issue](https://github.com/Microsoft/vscode/issues/34714) about it.
