### ISSUE TITLE
Add keyboard shortcuts in the tooltip

### ISSUE THREAD

**Issue by petruavram** [fabiospampinato/vscode-statusbar-debugger#7]
This is a small thing, given that the extension already makes great strides to improve usability of the debug functionality, but eventually I'd like to learn to use the keyboard for more repetitive tasks and having the keybinding in the tooltips when you rest the cursor over the icon are in my experience very neat way to reinforce learning and it's consistent across a large number of productivity applications UIs.

**Comment by fabiospampinato** [comment]
I would add support for this, but it's currently not possible to do with the provided APIs.

There was an issue about this in VSC's repository but I couldn't find it.
