### ISSUE TITLE
Consider other glyphs for debug bar

### ISSUE THREAD

**Issue by fcrespo82** [fabiospampinato/vscode-statusbar-debugger#9]
In my system the pause glyph was a little weird:

![screenshot from 2018-03-22 09-19-18](https://user-images.githubusercontent.com/462171/37770193-55a0e6ae-2db2-11e8-83b5-a3bcc49c807f.png)

So I came with this solution for me.

![screenshot from 2018-03-22 09-18-13](https://user-images.githubusercontent.com/462171/37770201-5b12eace-2db2-11e8-9bb5-f5f4326808e9.png)

The unicode for the glyphs are:

\u23f8 &#x23f8;
\u23f4 &#x23f4;
\u23f5 &#x23f5;
\u23f7 &#x23f7;
\u23f6 &#x23f6;
\u21ba &#x21ba;
\u23f9 &#x23f9;

The HTML representation is not accurate with the linux one. But serves as a guide.

Maybe you could add a option to replace the glyphs as a extension configuration.

Anyway thanks for the StatusBar Debugger, so much better that dealing with the floating bar.

**Comment by fabiospampinato** [comment]
Actually there's an icon for each one of those actions already embedded into VSC, except for the "pause" icon, so I made the best looking one I could using unicode characters, this is what it looks like in my system:

<img width="190" alt="screen shot 2018-03-22 at 13 32 32" src="https://user-images.githubusercontent.com/1812093/37770768-cd92dfaa-2dd5-11e8-9bd7-4d816b275b8a.png">

I like the idea of having a new `statusbarDebugger.actionsIcons` options, thanks for the suggesion.

I'll be happy to consider a PR for this.

**Comment by fabiospampinato** [comment]
@fcrespo82 In case you're working on the PR, I'd like it to work this way:

- `statusbarDebugger.actionsIcons` should be an array, having the same order as `statusbarDebugger.actions`.
- The default icons should be the `text` keys in [this object](https://github.com/fabiospampinato/vscode-statusbar-debugger/blob/8c3e521692f9820c2e8ef6f39faf86e21bcd4488/src/statusbar.ts#L56)

**Comment by fcrespo82** [comment]
Awesome, I was going to ask that!

**Comment by fcrespo82** [comment]
Just created the #10 pull request!
